#include <stdio.h>
#define EQP_PARA 512
#define BL_LENTH 4 
#define DQPN_NUM 16
#define DQSPN_NUM 4 

int SELIO;
int dut[EQP_PARA];
float IBISCURRUNT;
float IBISVAL[EQP_PARA][BL_LENTH][DQPN_NUM+DQSPN_NUM];
float IBISVALQS[EQP_PARA][BL_LENTH][DQPN_NUM+DQSPN_NUM];
float IBISBLAVG[EQP_PARA][BL_LENTH];
float IBISPNAVG[EQP_PARA][BL_LENTH];

int STEPCODE[EQP_PARA][BL_LENTH][DQPN_NUM+DQSPN_NUM];
int IBISFLG[EQP_PARA];
void CURRENTMEASURE(int *dut,float IBISVAL[EQP_PARA][BL_LENTH][DQPN_NUM+DQSPN_NUM]);


